[package]
name = "mlua-extras"
version = "0.1.0"
edition = "2021"

[features]
send = []
async = []

[dev-dependencies]
mlua = { version = "0.9.9", features = ["lua54", "vendored"] }

[dependencies]
# TODO: Update this when the derive crate is pushed
mlua_extras_derive = { path = "./mlua_extras_derive" }

mlua = { version = "0.9.9", features = ["async", "unstable"] }
parking_lot = { version = "0.12.3", features = ["send_guard"] }
parse = "0.1.2"
tealr = { version = "0.9.1", features = ["mlua"] }
hashbrown = "0.14.5"
