[package]
name = "mlua-extras"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
mlua = { version = "0.9.9", features = ["lua54", "vendored"] }

[dependencies]
mlua = { version = "0.9.9", features = ["async", "unstable"] }
parking_lot = { version = "0.12.3", features = ["send_guard"] }
parse = "0.1.2"
