[lib]
proc-macro = true

[package]
name = "mlua-extras-derive"
version = "0.1.0"
edition = "2021"

[dependencies]
proc-macro-error = "1.0.4"
proc-macro2 = { version = "1.0.86", features = ["span-locations"] }
quote = "1.0.37"
syn = "2.0.77"
venial = "0.6.0"
